Feat/ois/351 driftsmelding 3
Informasjonsforvaltning/fdk-portal pull request #1021
Opened 2021-08-30 07:36 UTC by oyvindis

2021-08-30 08:55 UTC, jeffreiffers requested changes

2021-08-30 08:55 UTC, jeffreiffers commented on package.json
> +    "@material-ui/core": "^4.12.3",
Vi skal helst ikke bruke material ui. Ser heller ikke hvor du bruker dette.

2021-08-30 10:18 UTC, oyvindis commented on package.json
> +    "@material-ui/core": "^4.12.3",
Jeg bruker @fellesdatakatalog/alert fra fdk-kit, den har definert @material-ui/icons under peerDependencies, den igjen krever @material-ui/core.

2021-08-30 11:09 UTC, oyvindis commented on package.json
> +    "@material-ui/core": "^4.12.3",
Jeg kan endre fellesdatakatalog/alert slik at ikke den lenger bruker material-ui, de ikonene kan jeg sikkert få fra Lene.

2021-08-30 14:21 UTC, matsjs commented on package.json
> +    "@material-ui/core": "^4.12.3",
Vet ikke hva slags alert ikon du er ute etter @oyvindis, men her er det en del som vi bruker ellers: https://drive.google.com/drive/folders/1q4ialddr9NarrXXPXcZixS0IS0tlJv-0

2021-09-01 09:35 UTC, oyvindis commented on package.json
> +    "@material-ui/core": "^4.12.3",
Fjernet avhengighet, PR oppdatert.

2021-09-01 09:54 UTC, jeffreiffers approved these changes

2021-09-02 06:11 UTC, matsjs approved these changes

2021-09-02 08:02 UTC, merged