Chore/jr/services messages
Informasjonsforvaltning/fdk-portal pull request #1138
Opened 2022-01-20 15:24 UTC by jeffreiffers

2022-01-21 08:52 UTC, oyvindis commented on src/entrypoints/publishing/router/publishing/index.tsx
> +  [`${PATHNAME_PUBLISHING}/service-messages/all`]: lazyWithRetry(
Er ikke denne det samme som den over, [`${PATHNAME_PUBLISHING}/service-messages`] ? Den over følger jo mer REST.

2022-01-21 08:59 UTC, oyvindis commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +            showAll ||
Denne filtreringen skal ikke gjøres her, men sendes inn som variabler til useGetServiceMessagesQuery. Så jeg ville foretrukket at du har en useEffect som da gjør en ny query basert på toggle. Det betyr at du også kan fjerne route-oppsett til ../all.

2022-01-21 09:05 UTC, oyvindis commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +        .sort(({ valid_from: fromA }, { valid_from: fromB }) => {
Foretrekker også her at sorteringen gjøres direkte i spørringen mot Strapi.
Det er ikke lagt inn mulighet for det nå, men ut fra dokumentasjon fra Strapi så skal det være mulig. Dvs. skal kunne defineres i filen /src/services/api/strapi/graphql/service-message.graphql og deretter generere på nytt, så skal det bli tilgjengelig som en parameter i useGetServiceMessagesQuery.

2022-01-21 09:07 UTC, oyvindis requested changes
Er mest optimalt om vi kan få til å styre filtrering og sortering direkte gjennom query mot Strapi, da blir frontend-koden ryddigere og det er sånn sett ikke behov for å definere egen route eller condition for "all/active", det styres bare som parameter i query.

2022-01-21 09:50 UTC, jeffreiffers commented on src/entrypoints/publishing/router/publishing/index.tsx
> +  [`${PATHNAME_PUBLISHING}/service-messages/all`]: lazyWithRetry(
Nei all viser alle og :id viser detail

2022-01-21 09:52 UTC, jeffreiffers commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +            showAll ||
Det krever da endring i strapi...

2022-01-24 11:20 UTC, oyvindis approved these changes

2022-01-24 11:25 UTC, merged