Refactor/por/new design
Informasjonsforvaltning/fdk-portal pull request #1239
Opened 2022-06-20 22:41 UTC by pooriamehregan

New design for: Latests posts from the Data Community

2022-06-21 06:25 UTC, oyvindis commented on src/components/community/container-footer/index.tsx
> +const ContainerFooter: FC<PropsWithChildren<Props>> = props => (
Her kan du heller gjøre:
const ContainerFooter: FC<PropsWithChildren<Props>> =({ href, children }) => (

Da kan du fjerne eslint-disable og trenger ikke si "props.href"

2022-06-21 06:28 UTC, oyvindis commented on src/components/community/container-footer/styled.ts
> +  padding-left: 10px;
På padding og margin får du den mer responsiv om du bruker "em", det blir da en faktor av font-size, som kan være bra hvis bruker har satt sin egen font-size i browser. Så prøv å bruke f.eks.:
padding-left: ${theme.spacing('S10')};

2022-06-21 06:29 UTC, oyvindis commented on src/components/community/container-header/styled.ts
> +  flex-direction: row;
flex-direction: row er default på flex så den er ikke nødvendig å oppgi.

2022-06-21 06:32 UTC, oyvindis commented on src/components/community/container-header/styled.ts
> +  width: 330px;
Kan tenkes at dette ikke fungerer like bra på mobil siden du setter denne bestemt til en bredde?
På flex er det fordel å ikke bruke 'width', men heller flex-basis.

2022-06-21 06:36 UTC, oyvindis commented on src/components/community/post/index.tsx
> +import TimeStamp from '../time-stamp/inde';
'../time-stamp/inde' er det skrivefeil?

2022-06-21 06:45 UTC, oyvindis commented on src/pages/main-page/main-page-pure.tsx
> +                      <Divider />
Vanligvis bedre å klare seg uten Divider-komponent. Du har to andre muligheter, enten lage en style på hver Post med border-bottom, eller lage en style på CommunityPosts f.eks.:

& > a { 
 border-bottom: ...
}

2022-06-21 06:46 UTC, oyvindis commented on src/components/community/truncated-ellipsis/index.tsx
> +// eslint-disable-next-line eslint-comments/disable-enable-pair
Kan fjerne eslint-disable kommentarer.

2022-06-21 06:55 UTC, oyvindis commented on src/components/community/truncated-ellipsis/styled.ts
> +  width: 290px;
Unngå å sette width da det skalerer dårlig.

Virker denne komponenten som du tenker? Ellipsis kan bare gjøres på en linje og da trenger du ikke sette høyden spesifikt. Hvis du ønsker at det skal fungere på en linje må du unngå at linjen brytes: 
white-space: nowrap;

2022-06-21 06:58 UTC, oyvindis requested changes
Oversiktlig PR, fint delt opp i små commits. Ser bra ut, jeg har noen kommentarer som du må se over. Meste er litt endring på styling, og gjør også en sjekk at styling skalerer fint i mobilvisning.

2022-06-21 10:53 UTC, pooriamehregan commented on src/components/community/post/index.tsx
> +import TimeStamp from '../time-stamp/inde';
Ja, jeg det var det.

2022-06-24 10:09 UTC, oyvindis approved these changes
Bra!

2022-06-24 10:18 UTC, pooriamehregan commented
Takk! :)

2022-06-24 10:18 UTC, merged