feat: show latest comments from Data Community
Informasjonsforvaltning/fdk-portal pull request #1245
Opened 2022-06-29 12:34 UTC by pooriamehregan

feat https://github.com/Informasjonsforvaltning/fdk-portal/issues/1244

2022-06-30 08:38 UTC, oyvindis commented on src/components/truncated-text/index.tsx
> +  setTruncateTrue?: boolean;
Anbefaler å følge en navnekonvensjon, da blir det veldig lesbart i koden. "setXXX" kan gjerne brukes for funksjoner, mens dette er en boolean. Jeg ville f.eks. kalt denne "isTruncate".

2022-06-30 08:42 UTC, oyvindis commented on src/components/truncated-text/index.tsx
> +        truncate={setTruncateTrue || (truncate && !expanded)}
setTruncateTrue ser ut som en initiell verdi som kommer som en prop. Du kan sette den initielle verdien med useState slik at du videre bare forholder deg til "truncate". Kan gjøre slik:

const [truncate, setTruncated] = useState(setTruncateTrue);

og da linje 48 forkortes til:
truncate={truncate && !expanded}

2022-06-30 08:44 UTC, oyvindis requested changes
Veldig bra! Bare gjør et par forenklinger der jeg har kommentert.

2022-06-30 10:13 UTC, pooriamehregan commented
Takk! Skal innføre endringene asap. :)

2022-07-01 06:13 UTC, oyvindis approved these changes

2022-07-01 08:09 UTC, merged