chore: get all reference data from new api
Informasjonsforvaltning/fdk-portal pull request #1258
Opened 2022-08-03 06:25 UTC by NilsOveTen

resolve #1250

2022-08-03 06:41 UTC, pooriamehregan approved these changes

2022-08-03 06:41 UTC, pooriamehregan commented on src/components/dataset-details-page/index.tsx
> +                      referenceTypes?.referenceTypes?.find(
Kanskje noen av (eventuelt begge) `referenceTypes` kunne ha et mer spesifikt navn?!

2022-08-03 06:52 UTC, NilsOveTen commented on src/components/dataset-details-page/index.tsx
> +                      referenceTypes?.referenceTypes?.find(
Kan vel kalle den ene `Container`, `Wrapper` elns. Men begge? Vi bruker vel navnet `referenceTypes` konsekvent i hele stacken?

2022-08-03 07:00 UTC, NilsOveTen commented on src/components/dataset-details-page/index.tsx
> +                      referenceTypes?.referenceTypes?.find(
e8d35a8 bedre sånn?

2022-08-03 07:37 UTC, stigbd approved these changes

2022-08-03 07:59 UTC, pooriamehregan commented on src/components/dataset-details-page/index.tsx
> +                      referenceTypes?.referenceTypes?.find(
Perfekt! 

> Kan vel kalle den ene `Container`, `Wrapper` elns. Men begge? Vi bruker vel navnet `referenceTypes` konsekvent i hele stacken?

Tja! Dette burde holde! Bra jobba!

2022-08-03 08:19 UTC, tenstad commented on src/components/with-reference-data/redux/saga.ts
> +  }
Vurdert `switch` og `case`?

2022-08-03 08:31 UTC, NilsOveTen commented on src/components/with-reference-data/redux/saga.ts
> +  }
vurderer heller å kjøre en liten refaktorering som fjerner media-type og linguistic-systems. Er rimelig sikker på at egentlig ikke er i bruk

2022-08-03 12:00 UTC, jeffreiffers requested changes

2022-08-03 12:00 UTC, jeffreiffers commented on src/components/dataset-details-page/index.tsx
>        getReferenceData('referencetypes');
Den finnes vel ikke lenger

2022-08-03 12:56 UTC, NilsOveTen commented on src/components/dataset-details-page/index.tsx
>        getReferenceData('referencetypes');
her refererer `getReferenceData` til `getReferenceDataRequested` fra with-reference-data, ikke til funksjonen jeg sletta i `api/referenceData.js`

2022-08-04 09:54 UTC, tenstad approved these changes

2022-08-05 06:44 UTC, NilsOveTen commented
Hadde litt problem med tema-filterene pga nye feltnavn fra new-reference-data, derfor 6816653

new review plz

2022-08-05 07:02 UTC, tenstad approved these changes

2022-08-05 07:56 UTC, pooriamehregan approved these changes

2022-08-05 08:08 UTC, terjesyl approved these changes

2022-08-05 09:51 UTC, merged