chore: upgrade strapi v4
Informasjonsforvaltning/fdk-portal pull request #1338
Opened 2022-10-17 06:17 UTC by jeffreiffers

2022-10-17 07:12 UTC, terjesyl commented on src/config.js
> +  FDK_CMS_BASE_URI: 'https://cms.staging.fellesdatakatalog.digdir.no',
Skal denne peke til staging?

2022-10-17 08:22 UTC, jeffreiffers commented on src/config.js
> +  FDK_CMS_BASE_URI: 'https://cms.staging.fellesdatakatalog.digdir.no',
Det er det som er default, siden resten peker til localhost så gir det mening og peke til staging. Vi har diskutert dette tidligere om default verdier skulle pekes til prod eller staging. Tror ikke vi har landet helt.

2022-10-17 08:42 UTC, tenstad commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +        ({ id, attributes }) =>
```suggestion
        ({ id, attributes: {title,
          message_type,
          valid_from,
          valid_to,
          short_description} }) =>
```
Kan man gjøre slik? Er det lurt? :D

2022-10-17 10:10 UTC, pooriamehregan commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +                  </Moment>{' '}
Er det nødvendig med disse tomme strengene etter closing tags?

2022-10-17 10:15 UTC, pooriamehregan commented on src/pages/news-article-page-v2/news-article-page.tsx
> +                <Moment format='DD.MM.YYYY'>{article?.publishedAt}</Moment>
format og url paths kan kansje også være definert som enums/konstanter?

2022-10-17 10:19 UTC, pooriamehregan commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +                  <Moment format='DD.MM.YYYY HH:mm'>
bruke enum?
```suggestion
                  <Moment format={moment.dateAndTime}>
```

2022-10-17 10:20 UTC, pooriamehregan commented on src/pages/news-article-page-v2/news-article-page.tsx
>                        {localization.lastChanged}{' '}
```suggestion
                      {localization.lastChanged}
```

2022-10-17 10:23 UTC, pooriamehregan requested changes
Jeg kommenterte under en del ting som kunne forbedres, ikke nødvendigvis kritiske endringer

2022-10-17 10:24 UTC, pooriamehregan approved these changes

2022-10-17 12:34 UTC, jeffreiffers commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +        ({ id, attributes }) =>
Fungerer ikke bra her, siden attributes kan være null/undefined. Da begynner typescript å klage.

2022-10-18 06:32 UTC, jeffreiffers commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +                  </Moment>{' '}
Dette er kode som ligger der fra før og har på måte ingenting med strapi v4 å gjøre.  Virker som man ønsker å ha mellomrom mellom fra og til dato her.

2022-10-18 06:32 UTC, jeffreiffers commented on src/entrypoints/publishing/router/publishing/pages/service-messages-page/index.tsx
> +                  <Moment format='DD.MM.YYYY HH:mm'>
Igjen har jeg ikke forholdt meg til kode optimalisering her men ja det kunne vært lurt å bruke enum hvis dato skal vises likt alle steder.

2022-10-18 06:32 UTC, jeffreiffers commented on src/pages/news-article-page-v2/news-article-page.tsx
>                        {localization.lastChanged}{' '}
Mellomrom er ønsket her. Som sakt dette har jeg ikke rørt på.

2022-10-18 08:43 UTC, merged