a11y(Summary): no empty heading
Informasjonsforvaltning/fdk-portal pull request #1495
Opened 2023-01-17 14:04 UTC by pooriamehregan

Fikser delvis https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/667
Resten av issuet skal været fikset av andre prer, relatert til [https://data.norge.no/public-services/](https://data.norge.no/public-services/a0db7475-6f3a-3cc5-ab9d-287433589a00) og Strapi

2023-01-17 16:18 UTC, MrFranzen approved these changes

2023-01-18 06:32 UTC, MrFranzen commented
Kanskje bare gjøre endring i denne PR, men sjekket linter feil, og virker som import gjerne vil ha siste filen også, uten extension. Det vil fikse feilen man får ved commit, se forslag på løsning som funker i min IDE:
linje 10 `import { MediaTypeOrExtent } from '../../../../types/domain.d';`

Er denne [linter regelen](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md) som gir feilen, litt lesing viser at kanskje det er ny konvensjon for å tilfredstille regel er å legge til selve filen og ikke bare mappen ved import 🤷🏼‍♂️

2023-01-18 06:33 UTC, MrFranzen requested changes
Kanskje bare gjøre endring i denne PR, men sjekket linter feil, og virker som import gjerne vil ha siste filen også, uten extension. Det vil fikse feilen man får ved commit, se forslag på løsning som funker i min IDE:
linje 10 `import { MediaTypeOrExtent } from '../../../../types/domain.d';`

Er denne [linter regelen](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md) som gir feilen, litt lesing viser at kanskje det er ny konvensjon for å tilfredstille regel er å legge til selve filen og ikke bare mappen ved import 🤷🏼‍♂️

2023-01-18 07:29 UTC, NilsOveTen approved these changes

2023-01-18 07:41 UTC, terjesyl approved these changes

2023-01-18 08:59 UTC, pooriamehregan commented
Godt forslag! Tror ikke det trengs lenger å navngi filene under types, har funnet en fiks. 
https://github.com/import-js/eslint-plugin-import/issues/2267

2023-01-18 12:00 UTC, MrFranzen approved these changes

2023-01-18 12:00 UTC, merged