Feat/ha/get most recent resources
Informasjonsforvaltning/fdk-portal pull request #1911
Opened 2024-03-06 15:01 UTC by hegeaal

closes  #1910

2024-03-06 15:10 UTC, NilsOveTen requested changes
Sett heller denne som draft til det er data i elastic

2024-03-06 15:10 UTC, NilsOveTen commented on src/api/search-fulltext-api/all-entities.ts
> +    // }
```suggestion
    sort: { will fail due to empty elastic
      field: 'FIRST_HARVESTED',
      direction: 'DESC'
    }
```

2024-03-19 06:49 UTC, jeffreiffers approved these changes

2024-03-19 07:39 UTC, NilsOveTen approved these changes

2024-03-19 07:48 UTC, merged