Add feature publicservices
Informasjonsforvaltning/fdk-portal pull request #653
Opened 2020-11-18 07:41 UTC by oyvindis

2020-11-18 09:21 UTC, azaxarov requested changes

2020-11-18 09:21 UTC, azaxarov commented on src/api/search-fulltext-api/publicservices.ts
> +import { searchFullTextApiPost } from './host';
Rename gjerne fil til: `src/api/search-fulltext-api/public-services.ts`

2020-11-18 09:21 UTC, azaxarov commented on src/api/search-fulltext-api/publicservices.ts
> +  searchFullTextApiPost('/publicservices', body);
Kan det være `/public-services` ?

2020-11-18 09:21 UTC, azaxarov commented on src/app/app.jsx
> +  PATHNAME_PUBLICSERVICES
PATHNAME_PUBLIC_SERVICES

2020-11-18 09:21 UTC, azaxarov commented on src/types/enums.ts
> +  publicservice
publicService

2020-11-18 09:21 UTC, azaxarov commented on src/components/with-public-services/index.tsx
> +const withOrganizationsCatalog = (Component: ComponentType<any>) => {
withPublicServices

2020-11-18 09:21 UTC, azaxarov commented on src/components/with-public-services/lib/fetch-helper.ts
> +export const shouldFetch = (metaState: any, queryKey: any) => {
Denne virker unødvndig

2020-11-18 09:21 UTC, azaxarov commented on src/pages/search-page/search-page-pure.tsx
> +      shouldFetch(publicServiceMetaData, publicServiceSearchParams)
Unødvendig sjekk med shouldFetch - bør alltid hente public services

2020-11-18 09:21 UTC, azaxarov commented on src/types/domain.d.ts
> +export interface PublicServiceData {
Denne trengs ikke, la redux bestemme hvordan data lagres og brukes

2020-11-18 09:21 UTC, azaxarov commented on src/pages/search-page/search-page-pure.tsx
> +  meta: publicServiceMetaData,
meta er ikke unik - jeg anbefaler å ikke bruke slike konsepter

2020-11-18 09:21 UTC, azaxarov commented on src/components/with-public-services/redux/reducer.ts
> +        })
Meta er ikke nødvendig

2020-11-18 09:21 UTC, azaxarov commented on src/components/with-public-services/redux/reducer.ts
> +        .set('publicServiceData', fromJS(action.payload.publicServiceData))
Det kan være bedre å lage en liste med public services adskilt fra paginering data om de

2020-11-18 09:21 UTC, azaxarov commented on src/components/with-public-services/redux/actions.ts
> +    }
Unødvendig komplikasjon

2020-11-18 14:00 UTC, oyvindis commented on src/pages/search-page/search-page-pure.tsx
> +      shouldFetch(publicServiceMetaData, publicServiceSearchParams)
Ja, søkesiden er ikke helt optimal, prøvde å unngå mye refaktoreing. useEffect har avhengighet mot søkeparameter, må gjøre ny get hver gang søkestreng endres. Søkestreng kommer ikke inn som en prop til komponenten, men defineres i const fra 'location' ved hver render. Denne søkestrenger er dependency til useEffect, noe som gjør at den trigges på ny flere ganger, komponenten ender opp i infinite loop. Meta-data hindrer at den gjør ny get hvis nettopp gjort.

En måte å unngå 'meta' på er kanskje å flytte useEffect inn i ResultsPage, et nivå ned fra 'SearchPage'? Men da først refaktorere til å bruke hoc på datasett, dataservice, concept og infomod i ResultsPage. Pluss det er litt mer som må refaktoreres og flyttes på søkesiden samtidig.

Enten ha som det er nå eller refaktorere på den måten som jeg foreslår. Eller har du annet forslag? @azaxarov

2020-11-19 07:14 UTC, oyvindis commented on src/components/with-public-services/redux/reducer.ts
> +        })
Fjernet

2020-11-19 09:19 UTC, azaxarov approved these changes

2020-11-19 13:47 UTC, merged