feat: show data service landing page
Informasjonsforvaltning/fdk-portal pull request #747
Opened 2021-01-29 10:45 UTC by azaxarov

2021-01-29 12:28 UTC, jeffreiffers requested changes

2021-01-29 12:28 UTC, jeffreiffers commented on src/components/data-service-details-page/index.tsx
> +  const landingPage = dataService?.landingPage?.[0];
```suggestion
  const [landingPage] = dataService?.landingPage || [];
```

2021-01-29 12:30 UTC, azaxarov commented on src/components/data-service-details-page/index.tsx
> +  const landingPage = dataService?.landingPage?.[0];
ikke noe gevinst av å bruke array destructuring, når vi vet vi skal alltid ha første element, synes jeg

2021-02-01 09:53 UTC, oyvindis approved these changes

2021-02-01 10:07 UTC, jeffreiffers approved these changes

2021-02-01 10:08 UTC, merged