feat: adds error pages and bounadies to app
Informasjonsforvaltning/fdk-portal pull request #813
Opened 2021-03-08 09:45 UTC by matsjs

2021-03-08 10:23 UTC, oyvindis commented on src/app/app.jsx
> +        <Route
Hva om du flytter denne et nivå høyere, at man slipper å definere dette på hver route? Ser at det fortsatt ligger en ErrorBoundary definert i /entrypoints/main/index.tsx. Kan den heller erstattes med den nye?

2021-03-08 11:19 UTC, matsjs commented on src/app/app.jsx
> +        <Route
Om jeg flytter den høyere vil en feil ta ned header og footer. Jeg kan evt lage en ny errorPage som også har med header og footer? Pushet en commit nå som bytter ut den gamle med den nye, men altså uten header og footer.

2021-03-08 12:08 UTC, oyvindis approved these changes

2021-03-08 13:28 UTC, azaxarov requested changes

2021-03-08 13:28 UTC, azaxarov commented on src/components/event-details-page/index.tsx
> +    throw new Error('404');
Usikker om det å kaste feil her er den beste løsningen

2021-03-08 13:28 UTC, azaxarov commented on src/components/information-model-details-page/index.tsx
> +    throw new Error('404');
Usikker om det å kaste feil her er den beste løsningen

2021-03-08 13:28 UTC, azaxarov commented on src/components/public-service-details-page/index.tsx
> +    throw new Error('404');
Usikker om det å kaste feil her er den beste løsningen

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-concept/index.tsx
> +    isLoading: state.ConceptReducer.get('isLoading')
isLoading må namespaces for å unngå kollisjon med andre data providere. isLoading => isLoadingConcept

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-concept/redux/reducer.ts
> +  isLoading: false
isLoading => isLoadingConcept

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-data-service/index.tsx
> +    isLoading: state.DataServiceReducer.get('isLoading')
isLoading => isLoadingDataService

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-data-service/redux/reducer.ts
> +  isLoading: false
isLoading => isLoadingDataService

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-dataset/index.tsx
> +  isLoading: boolean;
isLoading => isLoadingDataset

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-dataset/redux/reducer.ts
> +  isLoading: false
isLoading => isLoadingDataset

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-error-boundary/index.tsx
> +    <ErrorBoundary Fallback={fallback}>
```suggestion
    <ErrorBoundary fallback={fallback}>
```

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-error-boundary/error-boundary.tsx
> +    const { Fallback, children } = this.props;
```suggestion
    const { fallback: Fallback, children } = this.props;
```

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-error-boundary/error-boundary.tsx
> +  Fallback?: ComponentType<any>;
```suggestion
  fallback?: ComponentType<any>;
```

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-event/index.tsx
> +  isLoading: boolean;
isLoading => isLoadingEvent

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-event/redux/reducer.ts
> +  isLoading: false
isLoading => isLoadingEvent

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-information-model/redux/saga.ts
> +    const InformationModel = data as InformationModel;
```suggestion
    const informationModel = data as InformationModel;
```

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-information-model/redux/saga.ts
> +    if (InformationModel) {
```suggestion
    if (informationModel) {
```

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-public-service/index.tsx
> +  isLoading: boolean;
isLoading => isLoadingPublicService

2021-03-08 13:28 UTC, azaxarov commented on src/components/with-public-service/redux/reducer.ts
> +  isLoading: false
isLoading => isLoadingPublicService

2021-03-08 13:28 UTC, azaxarov commented on src/entrypoints/main/index.tsx
> +        <Route component={withErrorBoundary(ErrorPage)(ConnectedApp)} />
withErrorBoundary skal ikke brukes her. Flytt den heller til ConnectedApp

2021-03-08 13:28 UTC, azaxarov commented on src/components/error-page/styled.ts
> +  background-image: url(${LowerLeftBg}), url(${UpperRightBg});
Bruk gjerne JSX i stedet for background-image med url()

2021-03-08 13:28 UTC, azaxarov commented on src/components/error-page/styled.ts
> +const GlobalStyle = createGlobalStyle`
Ikke bruk createGlobalStyle her, gjør det gjerne i entrypoints/main/styles

2021-03-08 13:28 UTC, azaxarov commented on src/components/error-page/index.tsx
> +import Error500 from './components/error-500';
```suggestion
import React, { FC } from 'react';

import Error400 from './components/error-400';
import Error500 from './components/error-500';
```

2021-03-08 13:28 UTC, azaxarov commented on src/components/error-page/components/error-500/index.tsx
> +// 404 og 500
```suggestion
```

2021-03-08 13:28 UTC, azaxarov commented on src/components/error-page/components/error-500/index.tsx
> +import { getTranslateText as translate } from '../../../../lib/translateText';
```suggestion
import parse from 'html-react-parser';

import { convertToSanitizedHtml } from '../../../../lib/markdown-converter';
import translations from '../../../../lib/localization';
import { getTranslateText as translate } from '../../../../lib/translateText';
```

2021-03-08 13:28 UTC, azaxarov commented on src/components/error-page/components/error-500/index.tsx
> +    {parse(
Hvorfor bruke parse framfor å lage html struktur her?

2021-03-08 13:28 UTC, azaxarov commented on src/components/error-page/components/error-400/index.tsx
> +);
hvorfor er den tatt ut av JSX flow?

2021-03-08 13:28 UTC, azaxarov commented on src/components/error-page/components/error-400/index.tsx
> +  };
```suggestion
  const goBack = () => history.goBack();
```

2021-03-08 13:28 UTC, azaxarov commented on src/app/app.jsx
> +              component={withErrorBoundary(ErrorPage)(
Jeg synes det er renere å flytte withErrorBoundary ned et nivå

2021-03-08 15:26 UTC, matsjs commented on src/components/concept-details-page/index.tsx
> +    throw new Error('404');
Jeg kan i stedet for bare rendre 404 pagen hvis denne situasjonen oppstår - men da vil vi ikke få logget om en bruker trykker seg til en 404... Mener du det er overkill med error?

2021-03-08 16:09 UTC, matsjs commented on src/components/error-page/styled.ts
> +const GlobalStyle = createGlobalStyle`
Denne globale stilen gjelder da kun når errorPage rendres, hvordan funker det om den ikke er knyttet til errorPage?

2021-03-09 12:13 UTC, azaxarov requested changes

2021-03-09 12:13 UTC, azaxarov commented on src/app/breadcrumbs/concept-breadcrumb/concept-breadcrumb.jsx
> +        _.get(conceptItem, 'prefLabel') ?? translations.breadcrumb.notFound
Pass på her, siden dette er ikke en tsx fil. Anbefaler deg å konvertere til tsx, da kan du gjøre ting enda enklere:

```suggestion
        conceptItem?.prefLabel ?? translations.breadcrumb.notFound
```

2021-03-09 12:13 UTC, azaxarov commented on src/app/breadcrumbs/concept-breadcrumb/concept-breadcrumb.jsx
>    const { conceptItem } = props;
```suggestion
const PureConceptBreadcrumb = ({ conceptItem }) => {
```

2021-03-09 12:13 UTC, azaxarov commented on src/app/breadcrumbs/event-breadcrumb/index.tsx
> +  <span>{translate(event?.title) ?? translations.breadcrumb.notFound}</span>
Samme historie her: konverter gjerne til tsx

2021-03-09 12:13 UTC, azaxarov commented on src/components/error-page/index.tsx
> +    </SC.LowerLeftBackground>
Det trengs ikke en wrapper her, du kan like godt bruke samme stiler på SVGene

2021-03-09 12:13 UTC, azaxarov commented on src/components/error-page/styled.ts
> +const UpperRightBackground = styled.div`
Bruk da styled(DinSVG) for å slippe en ekstra wrapper

2021-03-10 14:15 UTC, azaxarov approved these changes

2021-03-10 16:29 UTC, merged