chore: refactor organization pages for new org-bff
Informasjonsforvaltning/fdk-portal pull request #862
Opened 2021-04-20 10:44 UTC by NilsOveTen

resolves #859 #839

2021-04-20 10:54 UTC, NilsOveTen commented on src/pages/organizations/pages/dataset-page/index.tsx
> -            {isAuthoritative && (
Det var ok å fjerne stjernen btw, sitat Joachim: `Det er ikke så viktig i denne sammenhengen.`

2021-04-20 11:11 UTC, azaxarov requested changes

2021-04-20 11:11 UTC, azaxarov commented on src/app/breadcrumbs/assessment-breadcrumb/index.tsx
> +  </span>
- span er ikke nødvendig her
- translations.breadcrumb.notFound trenger ikke være inne i translate()

```suggestion
  <>
    {translate(assessment?.entity?.title) ?? translations.breadcrumb.notFound}
  </>
```

2021-04-20 11:11 UTC, azaxarov commented on src/components/with-assessment/index.tsx
> +  hasMoreAssessments: boolean | false;
Det kan være fint å flytte disse ut i egen `withAssessments` komponent siden data struktur (array) stemmer ikke lenger med navnet

2021-04-20 11:11 UTC, azaxarov commented on src/components/with-assessment/index.tsx
> +  hasMoreAssessments: boolean | false;
```suggestion
  assessments: Assessment[];
  catalogRating: Rating | null;
  totalAssessments: number;
  assessmentsPage: number;
  assessmentPageSize: number;
  hasMoreAssessments: boolean;
```

2021-04-20 12:41 UTC, NilsOveTen commented on src/components/with-assessment/index.tsx
> +  hasMoreAssessments: boolean | false;
b39fb81

2021-04-20 12:41 UTC, NilsOveTen commented on src/components/with-assessment/index.tsx
> +  hasMoreAssessments: boolean | false;
b39fb81

2021-04-20 12:42 UTC, NilsOveTen commented on src/app/breadcrumbs/assessment-breadcrumb/index.tsx
> +  </span>
6e389e8

2021-04-20 14:42 UTC, azaxarov requested changes

2021-04-20 14:42 UTC, azaxarov commented on src/types/domain.d.ts
> +}
Generics to the rescue:

```suggestion
export interface Page<T> {
  content: T[];
  totalPages: number;
  totalElements: number;
  size: number;
  number: number;
}
```

2021-04-20 14:42 UTC, azaxarov commented on src/types/domain.d.ts
> +    new: number;
slike reserverte ord bør vi være forsiktig med - det kan godt erstattes av newCount eller lignende

2021-04-20 14:42 UTC, azaxarov commented on src/types/domain.d.ts
> +export interface OrgSummary {
OrganizationSummary?

2021-04-20 14:42 UTC, azaxarov commented on src/types/domain.d.ts
> +export interface OrgRating {
OrganizationRating? Alternativt et annet navt siden data strukturen er rikere enn bare rating

2021-04-20 14:42 UTC, azaxarov commented on src/pages/organizations/pages/organizations-page/index.tsx
> +          (translate(organization?.prefLabel) || organization?.name || '')
```suggestion
      ? organizations.filter(({ prefLabel, name }) =>
          (translate(prefLabel) ?? name ?? '')
```

2021-04-20 14:42 UTC, azaxarov commented on src/pages/organizations/pages/organizations-page/index.tsx
> +            { id, name, prefLabel, datasetCount, dataserviceCount }: OrgSummary,
Usikker, men typen bør være overflødig her

```suggestion
            { id, name, prefLabel, datasetCount, dataserviceCount },
```

2021-04-20 14:42 UTC, azaxarov commented on src/components/with-assessments/redux/actions.ts
> +  pagedAssessments: PagedAssessments
```suggestion
  page: Page<Assessment>
```

2021-04-20 14:42 UTC, azaxarov commented on src/components/with-assessments/redux/actions.ts
> +    }
Det kan være like greit å videresende page og hente ut data i reducer, siden action creator skal være dummest mulig

```suggestion
    payload: {
      assessments: pagedAssessments.content,
      totalAssessments: pagedAssessments.totalElements,
      assessmentPageSize: pagedAssessments.size,
      assessmentsPage: pagedAssessments.number,
      hasMoreAssessments:
        pagedAssessments.number + 1 < pagedAssessments.totalPages
    }
```

2021-04-20 14:42 UTC, azaxarov commented on src/components/with-assessments/redux/saga.ts
> +          context,
API parameter heter `contexts`

2021-04-20 14:42 UTC, azaxarov commented on src/components/with-assessments/redux/saga.ts
> +      yield put(actions.getPagedAssessmentsSucceeded(data as PagedAssessments));
```suggestion
      yield put(actions.getPagedAssessmentsSucceeded(data as Page<Assessment>));
```

2021-04-20 14:42 UTC, azaxarov commented on src/components/with-assessments/redux/saga.ts
> +          context,
```suggestion
          contexts,
```

2021-04-20 14:42 UTC, azaxarov commented on src/pages/organizations/pages/datasets-page/index.tsx
> +        isTransportportal ? 'NAP' : 'FDK',
Dette er vel contexts? I så fall skal enten være [FDK] eller [NAP]

2021-04-20 14:42 UTC, azaxarov commented on src/pages/organizations/pages/datasets-page/index.tsx
> +            {Array.from(assessments).map((assessment: Assessment) => (
```suggestion
            {assessments.map((assessment) => (
```

2021-04-21 06:35 UTC, NilsOveTen commented on src/pages/organizations/pages/datasets-page/index.tsx
> +        isTransportportal ? 'NAP' : 'FDK',
Du vil at det skal være string-array?

2021-04-21 06:35 UTC, NilsOveTen commented on src/pages/organizations/pages/datasets-page/index.tsx
> +            {Array.from(assessments).map((assessment: Assessment) => (
b25a394

2021-04-21 06:35 UTC, NilsOveTen commented on src/components/with-assessments/redux/saga.ts
> +          context,
4970480

2021-04-21 06:36 UTC, NilsOveTen commented on src/components/with-assessments/redux/saga.ts
> +          context,
4970480

2021-04-21 06:36 UTC, NilsOveTen commented on src/pages/organizations/pages/organizations-page/index.tsx
> +            { id, name, prefLabel, datasetCount, dataserviceCount }: OrgSummary,
b25a394

2021-04-21 06:36 UTC, NilsOveTen commented on src/pages/organizations/pages/organizations-page/index.tsx
> +          (translate(organization?.prefLabel) || organization?.name || '')
b25a394

2021-04-21 06:36 UTC, NilsOveTen commented on src/types/domain.d.ts
> +export interface OrgRating {
d69c1f2

2021-04-21 06:36 UTC, NilsOveTen commented on src/types/domain.d.ts
> +export interface OrgSummary {
d69c1f2

2021-04-21 06:36 UTC, NilsOveTen commented on src/types/domain.d.ts
> +    new: number;
0bc898d

2021-04-21 06:36 UTC, NilsOveTen commented on src/types/domain.d.ts
> +}
7ae5bb7

2021-04-21 06:37 UTC, NilsOveTen commented on src/components/with-assessments/redux/saga.ts
> +      yield put(actions.getPagedAssessmentsSucceeded(data as PagedAssessments));
7ae5bb7

2021-04-21 06:37 UTC, NilsOveTen commented on src/components/with-assessments/redux/actions.ts
> +  pagedAssessments: PagedAssessments
7ae5bb7

2021-04-21 06:46 UTC, NilsOveTen commented on src/components/with-assessments/redux/actions.ts
> +    }
f1bfe51

2021-04-21 06:59 UTC, azaxarov approved these changes

2021-04-21 08:28 UTC, merged