chore: add dotenv and prettierrc
Informasjonsforvaltning/fdk-portal pull request #957
Opened 2021-06-23 07:03 UTC by cobraz

Small developer improvement, adds a `.prettierrc` which makes it possible to use in-editor Prettier (like format on save etc).

Adds an example dotenv file, along with an gitignore entry for that file.

2021-06-23 07:16 UTC, jeffreiffers requested changes

2021-06-23 07:16 UTC, jeffreiffers commented on .env.example
> +SEARCH_API_HOST=https://www.staging.fellesdatakatalog.digdir.no
Kanskje fase ut det som står i config.js av dev verdier?

2021-06-23 12:19 UTC, cobraz commented on .env.example
> +SEARCH_API_HOST=https://www.staging.fellesdatakatalog.digdir.no
Tenker du på dette? https://github.com/Informasjonsforvaltning/fdk-portal/blob/0f432cdbe7b1354e2aea021cd5a267f47c8be3cd/src/config.js#L8-L20

2021-06-24 08:46 UTC, jeffreiffers commented on .env.example
> +SEARCH_API_HOST=https://www.staging.fellesdatakatalog.digdir.no
Ja

2021-06-30 06:00 UTC, oyvindis reviewed
Legger til fil ".env.example". Har allerede en fil .env, er det ikke bedre å bruke den?

2021-06-30 07:59 UTC, cobraz commented
> Legger til fil ".env.example". Har allerede en fil .env, er det ikke bedre å bruke den?

`.env` filen skal ikke sjekkes inn, så eksempel-fila er for nye utviklere for å sette opp sitt lokalmiljø.

2021-07-01 09:48 UTC, jeffreiffers approved these changes

2021-07-01 12:53 UTC, merged